version: "3"

services: 
    backend:
        container_name: backend
        restart: always
        build: 
            context: ./backend/
            dockerfile: ./Dockerfile
        ports: 
            - "5000:5000"
        command: "node index.js"

    frontend:
        build: 
            context: ./client/
            dockerfile: ./Dockerfile
        ports: 
            - "3000:3000"
        command: "npm start"
        links: 
            - backend